---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-ui-readlogs
  labels:
    name: k8s-ui-readlogs
    purpose: readlogs    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-readlogs-cl-config
  namespace: ns-ui-readlogs
  labels:
    app.kubernetes.io/name: k8s-ui-readlogs
    app.kubernetes.io/component: ui-readlogs-cl-config
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXhPVEl6TWpJd01Wb1hEVEk1TVRJeE5qSXpNakl3TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG9yCjdHc0t4bXp4WmtZVlpxUWJZc0RITDZDMUs4YjZqSDdFOGhUZ2V1aHNWSzhwaEM2SnhUNEU5U2NCN1c5NXY4eGkKMy9aMVV6WUdGRlFIWXhLVkJQa2dXRlFsbHhtMkU1UmJHL3lCMVZ1TitBOU9HNEVNNmxFWWVXU0gvYXNVbkpMSQp4RmVhbFZ5YndkS0xWQVY1VXpIUFlqa2Z1N3grOUtEcUk0UG1iSTB6T2IwTjQ1ZGJXVmw1OWN3Z1BXZlhBQmJYCkx2NWp0M09zdFh6UEhJMUQ0bHM0bmlPeStJOXJCN08rRkhEaVowSW5QeXlUamVITWV3WHJUczh5V0tQZXZlWFYKbmxpU1BJbXN4WGMzS2xyVUUrR0RPTTNVVmRKUnorSzB2Z1pLU25YUnBrVi9YMzR4emdGeGh2T0hibFdwN2pKdgp5a25PS2VaOVdmUW9ZNGYrWVhNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLcFl1QktGY1hJbzROdTc3L3hVdklxQnUvdzkKeExSOHZWNXBpNmVwQnZ5bHFBMUoxRFlndFJibHhPRE5PZm8xcEEvY1FIdTZibFZ1bTNuN01ibmVDSFl4d0FLQgpsZlhsblgwbEpSMmt6S0RNYStkVHUxU28yd1B6YzNCRkdVcUlaZHV5emxYWDhRYk03NzlzUnJxWjZoNTNqQ0NXClByQldlNVJoZjNsWVgwZXZLZW4wcHgzaUlHWWVaVXZCcjBQelA2eEZlQVdXelpoS21KdmdBN25NbnZkUXEvMjUKWnF4RUc0RjNhd1BwenZGYjVjaE9ESmMwYWd5eWRXMGd5bmVZMEFDcnNCZDBhS2VBSWg3eTlnc1VJcVRNZzZ4YQp3NkQ3cDFDRHBxRDgwRHd6N0piYWYrOHJmUFRtZmJoUzFRanZLZU93azZwRGhSbnpHaTgzSWdQcUFUQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://192.168.122.41:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJWWoyZWVPV0lZSmN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RFeU1Ua3lNekl5TURGYUZ3MHlNREV5TVRneU16SXlNRE5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdGSUJEVE5NdzFySkJVS24KOXdkZmgvcitkZ0NNd1FXWHFIS3BmU0w0T2xjRlNpWjBTV1g4Y2xVMlQ5blZRQXVPYVVOSTdGWFN0QVZPaE8zeApsQnhXNnhMTFFUdW9Ta0lvVWhsVWhoanJ2M2RnRGJpT2hTTXNRSDllbnRkWjBUdHdsWUlSeVh2TUJQS1hLM0hzCkprWHQ2dEFRdGFEdDd5UE0zNC9qWS93TS9DMGl4VDE2am4xcWk4VjU3VVFaV2NPSzF6KzRrUnNFUHBURmhQMmUKdTJMR20wRVFmdHZscEI3NGVrSzJSU01obUlSKzcvN3pzV1k1UytSVlg1Wk8vaFV1SExXS0ZLaTJpRTJmbUR5dQowYkNqY2hmQy9Jc3dVdWkwWjRYRndOcHdTb3VwOWI0ckVRVUNnS20xYW1FV1pHazd3NXpYdzN4U2hwcXFJa05CCmMvV0Nod0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDOWRQN0Vudm5ZZnU0eU1ZdkVhWWxXVmlNRUZXRTl2bWFPaQpTWVA4dm9vdkJTaGlORGUrR29YOU92V1ZFV2t0a1BRVzB0WWRUYkZZaXcrN0xhSEdDL25LYkhxbVU2SHlTSzBVCm9teVFQTDVpNyt5VEhxUWYyUTVwblk3Uzdmbm5FU0FMa25TYU1mRDdBTmJFRXVDOHZKcGMyVThydm9ZQjlaWUgKbkJlZXdSQjFvSHhIQWgxNVZJenlNeTVJKzJTajF5cXhNVXFMWlNXLzhEbTRYa0ptekVsNDkvUmZ6UUZ3TmFMeQpPbHdLdHJ5alhlckVNelgwUWcrdUhHRk1YUWZucXdiZFF5dWxxaXRsV1gyaXhmMGhPWHh3NjRySkFCZE9wcHBpCjNKUnJBdUlGbDJ5ZkhuWEpNNVFNY3FndEd5ZC9OQ1pKMk5WTG9STjRoczZSK3UyZUhCST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBd0ZJQkRUTk13MXJKQlVLbjl3ZGZoL3IrZGdDTXdRV1hxSEtwZlNMNE9sY0ZTaVowClNXWDhjbFUyVDluVlFBdU9hVU5JN0ZYU3RBVk9oTzN4bEJ4VzZ4TExRVHVvU2tJb1VobFVoaGpydjNkZ0RiaU8KaFNNc1FIOWVudGRaMFR0d2xZSVJ5WHZNQlBLWEszSHNKa1h0NnRBUXRhRHQ3eVBNMzQvalkvd00vQzBpeFQxNgpqbjFxaThWNTdVUVpXY09LMXorNGtSc0VQcFRGaFAyZXUyTEdtMEVRZnR2bHBCNzRla0syUlNNaG1JUis3Lzd6CnNXWTVTK1JWWDVaTy9oVXVITFdLRktpMmlFMmZtRHl1MGJDamNoZkMvSXN3VXVpMFo0WEZ3TnB3U291cDliNHIKRVFVQ2dLbTFhbUVXWkdrN3c1elh3M3hTaHBxcUlrTkJjL1dDaHdJREFRQUJBb0lCQUFXb1krK0hldEtrY1JWKwppSUp6N1JPTEJzRmg4c0lhOEFNOG5FL2FINE5YM0FmNmFhRmZKcllXVzZxdHRlQlVkclFTRHFzbE96V2drbGJHCnlUeWFPTlJoa1NreUlCbFBLUENCWGtNenFIdlJmem5vSEFrK3A2YWVHS0tEbzFqTWJ0dDNJQjdWVFlNM3Y4cS8KWnpzWkE0N000REQzc3dnOS9XRDJVckkyVUF0N0cxS2Rremd1UzRGUjh1RWVhTmttZ3V2cmVYK21LNWZpNXdscQpmZXIvTGhucDRxK0lCS2JXa0JNcmxUR0xDcklvNXRLNE95MXkzSk1EZ05CWXZUM3A3U3IybHNLT1lhdWJ5NWpGCnQ5Q05LU0dHR215bXp6Y25BN0VrT1BqMFBhWXZGaEtrTjljdVVSU01LYnNVUTRPQTdJVGUrY1VZMndyT284eXoKMHBiYks4RUNnWUVBOWgzbGpBYkdpaXc1OVZJdkV5aS9KSXJQY3FwK203bjVTaTR6S0JCRVhBTXBzUTVwajhCRQo0TlpWTlZ4SHhFWk16eEVUa1R0WWYxR2VWOEZjNnp2eElETE4rNkxIaTlVQThQTXgxbUt3aWIzc0RRRTk3Q2hPCmRXN2lsNEhrMGdsSmg1TmNzcFZIVkU5d1FqbVh6cEIrUGpTdlZUVmtyeVR2cGJmdjZTY21ack1DZ1lFQXlBc1QKTEhBazNDemxRRGNQYzZraXFmV01PKzBIUTVqOVdkWU9pUTlhMFh4NWpPMXVsK2Fjb0hCMFhCemdIT1ZrSzZ3Twp0NytiekZGZDZmeU9zR3NseFFnMTd2VHFLbStuRkFOb1BxTnpxVWZzZzdESCtRU1l6bHBmK3BJdktpWVMxSngvCjhqQ1JDQm80bmNma0JmL3hYR1A1WUFYRzQ3RWMzS3NzSXRVU3Z0MENnWUVBdXhYNjJqaUVUNkJTNW5MMHFlRzkKZXUreHhmNW9nOFFaQmhTY2VvWHpFT2F1bUpMV0Y1b1dRYnRyeGtaQm42ZTQxMmFwc3lxam1SVFlBdWxQMHRrYgo4RmZ1VUt4cWQ1Y1JRaGY3K0hYSXNNd1lWY0p0NmNpeDYzN0E3RjZuTENvM0pNSVdJd0pxMkdJU2VhVUNDdG0zCnZWMmJNbkNGK3NWZkRtQUdGUHZYcXhVQ2dZQnlhTE1jbFQ3ZmxlVy9wajMySG1PdTVMckJnenpHVW5lRHE4TkEKYkVHNjBnQUtzN2l1czd3Y25uUk9RazJDK1Vjakd4S0gwTlJnTktFTHMrQS8wZWdXR2k0T2JwQ0dtTGpyMzA3OQpsQ29RUlF4bC9QTkIzbmt1ZTgyczEzS1dIcFJpZU9kTU1xNmYvYThudmkwUnFXSDNQMDVldHE4YmhpNUZucmh0CmE0Ti9HUUtCZ1FDUDZNTXUyaTVEc3hBMkFvRVZzamQ5eUkyZzlpZ2Q3RVZaTkJscnQ3T0VUOURFeGhpSDFpZDUKVW13RmN6RGMreDV6R1gzY0p5RXgzaWFsM1F0K0tCT01lby9vN21NOGJ2NE9ucU44Y0dSenc3ayt4NDhZTVlnVQozRFJkbTlyWDN3MDBsTjlmd0ROZ3Y0WFZPQzNaVVJhKzdkNWpNdjBEamsyNFhOQy9KcC9DWFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-readlogs-deployment
  namespace: ns-ui-readlogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ui-readlogs
  template:
    metadata:
      labels:
        app: k8s-ui-readlogs
    spec:
      containers:
        - name: k8s-ui-readlogs
          image: atamdocker/k8s-ui-readlogs:latest
          args:
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cluster-config
              mountPath: /root/.kube/

      volumes:
        - name: cluster-config
          configMap:
            defaultMode: 420
            name: ui-readlogs-cl-config
---
apiVersion: v1
kind: Service
metadata:
  name: ui-readlogs-service
  namespace: ns-ui-readlogs
  annotations:
      ui-readlogs/scrape: 'true'
      ui-readlogs/port:   '8080'
spec:
  selector:
    app: k8s-ui-readlogs
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  type: NodePort